version: '3'

services:
  jenkins:
    restart: unless-stopped
    container_name: jenkins
    image: jenkins/jenkins:lts
    command: [ "--prefix=/jenkins/" ]
    ports:
      - '127.0.0.1:7080:8080'
      - '127.0.0.1:50000:50000'
    volumes:
      - ./data/jenkins/home:/var/jenkins_home

  jenkins-agent-one:
    restart: unless-stopped
    container_name: jenkins-agent-one
    image: jenkins/inbound-agent
    environment:
      JENKINS_URL: "http://host.docker.internal:7080/jenkins/"
      JENKINS_TUNNEL: "host.docker.internal:50000"
      JENKINS_AGENT_NAME: "jenkins-agent-one"
      JENKINS_SECRET: "@/home/jenkins/secret-file"
      JENKINS_AGENT_WORKDIR: "/home/jenkins/agent"
      JENKINS_WEB_SOCKET: "false"
    volumes:
      - ./data/jenkins/agents/one:/home/jenkins/agent
      - ./data/jenkins/agents/secrets/jenkins-agent-one.txt:/home/jenkins/secret-file:ro
    depends_on:
      - jenkins

  jenkins-agent-two:
    restart: unless-stopped
    container_name: jenkins-agent-two
    image: jenkins/inbound-agent
    environment:
      JENKINS_URL: "http://host.docker.internal:7080/jenkins/"
      JENKINS_TUNNEL: "host.docker.internal:50000"
      JENKINS_AGENT_NAME: "jenkins-agent-two"
      JENKINS_SECRET: "@/home/jenkins/secret-file"
      JENKINS_AGENT_WORKDIR: "/home/jenkins/agent"
      JENKINS_WEB_SOCKET: "false"
    volumes:
      - ./data/jenkins/agents/two:/home/jenkins/agent
      - ./data/jenkins/agents/secrets/jenkins-agent-two.txt:/home/jenkins/secret-file:ro
    depends_on:
      - jenkins

  sonarqube:
    restart: unless-stopped
    container_name: sonarqube
    image: sonarqube:lts
    ports:
      - '127.0.0.1:9000:9000'
    environment:
      - sonar.web.context=/sonarqube
    volumes:
      - ./data/sonarqube/data:/opt/sonarqube/data
      - ./data/sonarqube/extensions:/opt/sonarqube/extensions
      - ./data/sonarqube/logs:/opt/sonarqube/lib/bundled-plugins
      - ./data/sonarqube/plugins/sonarqube-community-branch-plugin-1.3.2.jar:/opt/sonarqube/extensions/plugins/sonarqube-community-branch-plugin.jar
      - ./data/sonarqube/plugins/sonarqube-community-branch-plugin-1.3.2.jar:/opt/sonarqube/lib/common/sonarqube-community-branch-plugin.jar
