version: '3'

services:
  minio:
    restart: unless-stopped
    container_name: s3-minio
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    ports:
      - '127.0.0.1:9000:9000'
      - '127.0.0.1:9001:9001'
    volumes:
      - ./data:/data
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: adminpwd
