version: '3'

services:
  pure-ftpd:
    restart: unless-stopped
    container_name: pure-ftpd
    image: stilliard/pure-ftpd
    ports:
      - '127.0.0.1:10021:21'
      - '127.0.0.1:30000-30009:30000-30009'
    volumes:
      - ./data:/home/username/
      - ./data/passwd:/etc/pure-ftpd/passwd
    environment:
      PUBLICHOST: "localhost"
      FTP_USER_NAME: username
      FTP_USER_PASS: mypass
      FTP_USER_HOME: /home/username
