version: '3'

services:
  keycloak:
    restart: unless-stopped
    container_name: keycloak
    image: quay.io/keycloak/keycloak:latest
    ports:
      - '127.0.0.1:18080:8080'
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=adminpwd
    command: start-dev
