version: '3'

services:
  postgresql:
    restart: unless-stopped
    container_name: postgresql
    image: postgres:latest
    ports:
      - '127.0.0.1:5432:5432'
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpwd
