version: '3'

services:
  ibm-mq:
    platform: linux/amd64
    restart: unless-stopped
    container_name: ibm-mq
    image: ibmcom/mq:latest
    ports:
      - '127.0.0.1:1414:1414'
      - '127.0.0.1:9443:9443'
    volumes:
      - ./data:/mnt/mqm
    environment:
      LICENSE: accept
      MQ_QMGR_NAME: QM1
      MQ_APP_PASSWORD: passw0rd
