version: '3'

services:
  mariadb:
    restart: unless-stopped
    container_name: mariadb
    image: mariadb:latest
    ports:
      - '127.0.0.1:3306:3306'
    volumes:
      - ./data:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: rootpwd
